version: 2
jobs:
 build:
   machine:
    docker_layer_caching: true    # default - false
   steps:
     - checkout
     - setup_remote_docker: 
         docker_layer_caching: true
     - run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASS
     - run: docker build -t gleandroj/laravel:android .
     - run: docker push gleandroj/laravel:android
# Fluxo do CircleCI
workflows:
  version: 2
  build_release:
    jobs:
     - build