version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - setup_remote_docker: 
         docker_layer_caching: true
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASS
     # build the application image
     - run: docker build -t gleandroj/laravel:latest .
     # deploy the image
     - run: docker push gleandroj/laravel:latest
# Fluxo do CircleCI
workflows:
  version: 2
  build_release:
    jobs:
     - build