version: 2
jobs:
 build:
   machine:
    docker_layer_caching: true    # default - false
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASS
     # build the application image
     - run: docker build -t gleandroj/laravel:wine .
     # deploy the image
     - run: docker push gleandroj/laravel:wine
# Fluxo do CircleCI
workflows:
  version: 2
  build_release:
    jobs:
     - build